INSERT INTO categoria_servico VALUES (1, 'NUTRICIONISTA');
INSERT INTO categoria_servico VALUES (2, 'DENTISTA');
INSERT INTO categoria_servico VALUES (3, 'FISIOTERAPEUTA');
INSERT INTO categoria_servico VALUES (4, 'CABELEIREIRO');
INSERT INTO categoria_servico VALUES (5, 'MANICURE');
INSERT INTO categoria_servico VALUES (6, 'ESTETICITA');


INSERT INTO servico VALUES (1, 1, 'TERAPIA ALIMENTAR');
INSERT INTO servico VALUES (3, 2, 'CONSULTA');
INSERT INTO servico VALUES (2, 3, 'TRATAMENTO DE CANAL');
INSERT INTO servico VALUES (4, 4, 'CORTE');
INSERT INTO servico VALUES (4, 5, 'ESCOVA');
INSERT INTO servico VALUES (4, 6, 'TINTURA');
INSERT INTO servico VALUES (5, 7, 'UNHA MÃO');
INSERT INTO servico VALUES (5, 8, 'UNHA PÉ');
INSERT INTO servico VALUES (5, 9, 'UNHA PÉ/MÃO');
INSERT INTO servico VALUES (6, 10, 'LIMPEZA DE PELE');
INSERT INTO servico VALUES (6, 11, 'MASSAGEM MODELADORA');